import { BrandDeal } from "@/lib/types";

export const brandDeals: BrandDeal[] = [
  // Completed
  {
    id: "deal-1",
    brandName: "Glossier",
    brandInitials: "GL",
    industry: "Skincare",
    value: 2500,
    status: "completed",
    matchPercentage: 95,
    matchReasons: ["Perfect niche alignment", "Similar audience demographics", "Previous collaboration success"],
    suggestedRate: { min: 2200, max: 3000 },
    deliverables: ["1 YouTube video", "2 TikToks", "3 Stories"],
    contactName: "Sarah Chen",
    contactEmail: "sarah@glossier.com",
    lastActivity: "2025-12-15",
    daysSinceActivity: 88,
    notes: "Great experience, open to future collabs",
  },
  {
    id: "deal-2",
    brandName: "CeraVe",
    brandInitials: "CV",
    industry: "Skincare",
    value: 3000,
    status: "completed",
    matchPercentage: 92,
    matchReasons: ["Top skincare brand", "Educational content fit", "High engagement niche"],
    suggestedRate: { min: 2800, max: 3500 },
    deliverables: ["1 YouTube review", "1 TikTok", "1 Instagram Reel"],
    contactName: "Mike Johnson",
    contactEmail: "mike@cerave.com",
    lastActivity: "2026-01-20",
    daysSinceActivity: 52,
    notes: "Annual partnership potential",
  },
  {
    id: "deal-3",
    brandName: "The Ordinary",
    brandInitials: "TO",
    industry: "Skincare",
    value: 1800,
    status: "completed",
    matchPercentage: 88,
    matchReasons: ["Budget-friendly angle", "Science-based approach matches content style"],
    suggestedRate: { min: 1500, max: 2200 },
    deliverables: ["2 TikToks", "1 Blog post"],
    contactName: "Lisa Park",
    contactEmail: "lisa@theordinary.com",
    lastActivity: "2025-11-30",
    daysSinceActivity: 103,
    notes: "Quick turnaround, good creative freedom",
  },
  {
    id: "deal-4",
    brandName: "Fenty Skin",
    brandInitials: "FS",
    industry: "Skincare & Beauty",
    value: 2200,
    status: "completed",
    matchPercentage: 85,
    matchReasons: ["Inclusive beauty alignment", "High-profile brand boost"],
    suggestedRate: { min: 2000, max: 2800 },
    deliverables: ["1 YouTube video", "1 TikTok"],
    contactName: "Jordan Williams",
    contactEmail: "jordan@fentybeauty.com",
    lastActivity: "2026-02-10",
    daysSinceActivity: 31,
    notes: "Loved the creative direction",
  },
  {
    id: "deal-5",
    brandName: "Tatcha",
    brandInitials: "TA",
    industry: "Luxury Skincare",
    value: 2800,
    status: "completed",
    matchPercentage: 82,
    matchReasons: ["Premium positioning", "Aspirational audience overlap"],
    suggestedRate: { min: 2500, max: 3200 },
    deliverables: ["1 YouTube video", "2 TikToks", "1 Instagram Reel"],
    contactName: "Emma Davis",
    contactEmail: "emma@tatcha.com",
    lastActivity: "2026-01-05",
    daysSinceActivity: 67,
    notes: "Premium brand, higher production expectations",
  },
  // Pipeline
  {
    id: "deal-6",
    brandName: "Fresh",
    brandInitials: "FR",
    industry: "Skincare",
    value: 3500,
    status: "negotiating",
    matchPercentage: 90,
    matchReasons: ["Natural ingredients focus", "Audience interest in clean beauty", "Strong engagement metrics"],
    suggestedRate: { min: 3200, max: 4000 },
    deliverables: ["1 YouTube video", "3 TikToks", "1 Instagram Reel"],
    contactName: "Alex Rivera",
    contactEmail: "alex@fresh.com",
    lastActivity: "2026-03-10",
    daysSinceActivity: 3,
    notes: "Counter-offered at $3,500, waiting on approval",
  },
  {
    id: "deal-7",
    brandName: "Drunk Elephant",
    brandInitials: "DE",
    industry: "Skincare",
    value: 4000,
    status: "pitched",
    matchPercentage: 87,
    matchReasons: ["Clean beauty pioneer", "Viral product potential", "Premium audience match"],
    suggestedRate: { min: 3500, max: 4500 },
    deliverables: ["1 YouTube deep-dive", "2 TikToks", "2 Stories"],
    contactName: "Rachel Kim",
    contactEmail: "rachel@drunkelephant.com",
    lastActivity: "2026-03-08",
    daysSinceActivity: 5,
    notes: "Sent pitch deck, follow up next week",
  },
  {
    id: "deal-8",
    brandName: "Sunday Riley",
    brandInitials: "SR",
    industry: "Luxury Skincare",
    value: 3200,
    status: "prospect",
    matchPercentage: 84,
    matchReasons: ["Luxury skincare niche", "Product efficacy focus", "Growing brand presence"],
    suggestedRate: { min: 2800, max: 3800 },
    deliverables: ["TBD"],
    contactName: "Tom Baker",
    contactEmail: "tom@sundayriley.com",
    lastActivity: "2026-03-12",
    daysSinceActivity: 1,
    notes: "Initial research — strong fit for Q2 campaign",
  },
];
